import React from 'react';
import { PageHero } from '../components/PageHero';
import { Reveal } from '../components/Reveal';
import { BRAND } from '../content';

const LAST_UPDATED = 'August 21, 2026';

const SECTIONS = [
  {
    heading: '1. Acceptance of Terms',
    body: (
      <p>
        These Terms of Service ("Terms") govern your access to and use of {BRAND.domain} and any
        related services operated by {BRAND.name} ("{BRAND.name}", "we", "us", or "our"). By
        accessing our site, submitting a catalog, or otherwise using our services, you agree to be
        bound by these Terms. If you do not agree, do not use the site or services.
      </p>
    ),
  },
  {
    heading: '2. Who These Terms Apply To',
    body: (
      <p>
        These Terms apply to all visitors to our website. Artists who submit catalog material for
        acquisition, and AI companies or enterprise buyers who license catalog material, are also
        governed by a separate signed agreement (a rights-grant agreement for artists, or a
        licensing agreement for buyers). Where a conflict exists between these Terms and a signed
        agreement, the signed agreement controls for the matters it covers.
      </p>
    ),
  },
  {
    heading: '3. The Service',
    body: (
      <p>
        {BRAND.name} acquires training and licensing rights to artist music catalogs, prepares
        catalog material (including mastering and stem separation) for licensing, verifies chain of
        title, and makes cleared catalog available to AI platforms and enterprise licensees. In
        exchange, artists whose catalogs are acquired receive a revenue split on the mechanical
        royalties or licensing revenue generated by that use, as set out in their individual
        rights-grant agreement.
      </p>
    ),
  },
  {
    heading: '4. Artist Submissions and Rights Grants',
    body: (
      <>
        <p>
          By submitting a track, catalog, or related materials (including audio files, metadata,
          and ownership documentation) through our upload, apply, or vault tools, you represent and
          warrant that you own or control the rights necessary to submit that material and to grant
          {' '}{BRAND.name} the rights described in your rights-grant agreement, and that the material
          does not infringe any third party's rights.
        </p>
        <p>
          Acceptance of a submission into the {BRAND.name} catalog, the scope of rights granted, and
          the applicable royalty or revenue split are governed by the specific rights-grant
          agreement signed by the artist, not by these Terms alone. Submission of material does not
          guarantee acceptance into the catalog or any licensing outcome.
        </p>
      </>
    ),
  },
  {
    heading: '5. AI and Enterprise Licensing',
    body: (
      <p>
        AI companies and enterprise buyers who wish to license catalog material for training or
        other use must enter into a separate licensing agreement with {BRAND.name} specifying scope
        of use, territory, term, and compensation. Nothing on this website constitutes an offer to
        license specific material; licensing terms are established only through a signed agreement.
      </p>
    ),
  },
  {
    heading: '6. Payments and Royalties',
    body: (
      <p>
        Where an artist's rights-grant agreement provides for a revenue split, {BRAND.name} will
        calculate and pay amounts owed on the schedule and using the methodology set out in that
        agreement. Artists are responsible for keeping accurate, current payout and tax information
        on file with us. Disputes about calculation or payment should be raised in writing to{' '}
        <a href={`mailto:${BRAND.email}`} className="text-cyan hover:underline">
          {BRAND.email}
        </a>
        .
      </p>
    ),
  },
  {
    heading: '7. Acceptable Use',
    body: (
      <p>
        You agree not to misuse the site or services, including by attempting to access accounts or
        data that are not yours, uploading material you do not have rights to, interfering with the
        operation or security of the site, or using the site to submit false ownership or
        chain-of-title information.
      </p>
    ),
  },
  {
    heading: '8. Intellectual Property',
    body: (
      <p>
        The {BRAND.name} name, logo, and website content (excluding artist-submitted catalog
        material, which remains subject to the applicable rights-grant agreement) are owned by{' '}
        {BRAND.name} or its licensors and may not be used without permission.
      </p>
    ),
  },
  {
    heading: '9. Disclaimers',
    body: (
      <p>
        The website and services are provided "as is" without warranties of any kind, to the
        fullest extent permitted by law. We do not guarantee that any submitted catalog will be
        accepted, licensed, or generate any particular amount of revenue.
      </p>
    ),
  },
  {
    heading: '10. Limitation of Liability',
    body: (
      <p>
        To the fullest extent permitted by law, {BRAND.name} will not be liable for indirect,
        incidental, special, consequential, or punitive damages arising out of or related to your
        use of the site or services. Nothing in these Terms limits liability that cannot be limited
        under applicable law.
      </p>
    ),
  },
  {
    heading: '11. Changes to These Terms',
    body: (
      <p>
        We may update these Terms from time to time. Continued use of the site after an update
        constitutes acceptance of the revised Terms. Signed rights-grant or licensing agreements are
        only modified in writing.
      </p>
    ),
  },
  {
    heading: '12. Contact Us',
    body: (
      <p>
        Questions about these Terms can be sent to{' '}
        <a href={`mailto:${BRAND.email}`} className="text-cyan hover:underline">
          {BRAND.email}
        </a>
        .
      </p>
    ),
  },
];

const TermsPage = () => (
  <div data-testid="terms-page">
    <PageHero
      testid="terms-hero"
      label="Legal"
      title="Terms of Service"
      subtitle={`Last updated ${LAST_UPDATED}`}
    />

    <section className="bg-ink py-20 lg:py-28">
      <div className="mx-auto max-w-3xl px-6 lg:px-8">
        <Reveal>
          <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-6 text-sm leading-relaxed text-slate-400 md:p-8">
            This page is a general-purpose Terms of Service template for {BRAND.name} and has not
            yet been reviewed by legal counsel. Please have an attorney familiar with music rights,
            licensing, and AI training-data agreements review it — especially the rights-grant and
            royalty-split language — before this page is relied on as binding.
          </div>
        </Reveal>

        <div className="mt-12 space-y-12">
          {SECTIONS.map((s) => (
            <Reveal key={s.heading}>
              <h2 className="font-heading text-xl font-semibold text-white sm:text-2xl">
                {s.heading}
              </h2>
              <div className="mt-4 space-y-4 text-base leading-relaxed text-slate-400">
                {s.body}
              </div>
            </Reveal>
          ))}
        </div>
      </div>
    </section>
  </div>
);

export default TermsPage;
